# Generated by Django 2.1 on 2018-12-10 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monoku', '0002_auto_20181210_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galguerias',
            old_name='tipo_producto',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='preferecias_galguerias',
            old_name='nombre_persona',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='preferecias_galguerias',
            old_name='nombre_producto',
            new_name='producto',
        ),
        migrations.AddField(
            model_name='preferecias_galguerias',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galguerias',
            name='cantidad_producto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='galguerias',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personas',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preferecias_galguerias',
            name='cantidad_consumido',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
